### ISSUE TITLE
Logout button has a wrong Label

### ISSUE THREAD

**Issue by KunzRobert** [danieljancar/chorizo#31]
## Logout button in course detail has a wrong label

In Course detail the logout button has the label "Button" which is wrong

- Package: Course 

## Expected Behavior

The button should have the label "Logout"

## Actual Behavior

The button has the label "Button"

**Comment by danieljancar** [comment]
@KunzRobert, 
The navbar for course detail hasn't been worked on yet, and still has to be defined properly. We don't know what buttons and navigation items will be displayed on the course detail navbar. It will certainly be different from the course overview navbar. 😉
