### ISSUE TITLE
Links in course detail not working and wrong label

### ISSUE THREAD

**Issue by KunzRobert** [danieljancar/chorizo#33]
## Links in course detail not working and wrong label

In course detail in the navigation bar the links/ routes have the wrong label, and if you click on them they don't redirect you to the coresponding page

- Package: Course 

## Expected Behavior

The links should have the correct Label, and redirect you to the coresponding page

## Actual Behavior

The Links have the wrong label, and don't redirect you anywhere

# Additional Information

![image](https://github.com/danieljancar/chorizo/assets/111433522/6713e5e5-531e-4a89-b5a3-72b299b07e0c)

**Comment by danieljancar** [comment]
As already stated in #31 and issued on #26.
