### ISSUE TITLE
Improve latest courses on homepage

### ISSUE THREAD

**Issue by danieljancar** [danieljancar/chorizo#35]
## Description

We need to add a link, to the appropriate course route and improve layout and add additional fields like `createdAt` date with `DatePipe`

- Package: course

**Comment by valeriaxxx** [comment]
@danieljancar Was meinst du mit dem Link? Wenn man darauf klickt oder wie genau? Könntest du es bitte ein bisschen spezifischer machen?

**Comment by danieljancar** [comment]
@valeriaxxx, as we see, the `routerLink` to the appropraite course is already implemented. So what is missing?

> Additional field for `createdAt` like we have it on `courses-overview.component`, probably below the description.

**Comment by danieljancar** [comment]
I did, issue closed. 🚀
