### ISSUE TITLE
 Create responsive navbar

### ISSUE THREAD

**Issue by KunzRobert** [danieljancar/chorizo#4]
# Implement responsive navbar

## Description

Implement a responsive navigation bar similar to the provided design mockups. The navbar should adapt to three different breakpoints: large, medium, and small.

**Requirements:**

- Large Screens: Display the full navigation bar with course title and navigation links.
- Medium Screens: Show a collapsible menu icon and centralize essential icons.
- Small Screens: Prioritize menu icon and essential features, hide secondary items.

- Package: course 

# Additional Information

Figma Mockups: [Responsive Navbar Design](https://www.figma.com/file/oarKaGgevt8SQNcB2w4Lbr/Mockups?type=design&node-id=3-4&mode=design&t=isx0krW9d8KvOQx0-0)
Ensure the navbar is accessible and follows best practices for usability.

**Comment by danieljancar** [comment]
Make sure to use the `sidenav` from angular material for smaller screens found here: https://material.angular.io/components/sidenav/overview
