### ISSUE TITLE
Gap between text on the homepage missing

### ISSUE THREAD

**Issue by KunzRobert** [danieljancar/chorizo#45]
## Gap between text on the homepage missing

On the homepage there is a section, which displays the features of chorizo. But after these features there is a gap missing and the text seems to be too close together. In the screenshot you will see what exactly I mean

- Package: Course 

# Additional Information

Screenshot of the missing space:

Gap between text on the homepage missing space:

![image](https://github.com/danieljancar/chorizo/assets/111433522/01de7c51-292f-4a48-9719-5c7f25d38e20)

**Comment by danieljancar** [comment]
@KunzRobert,
This is a markdown text issue and not a code related issue, please close the issue as it's not relevant to the markdown renderer and will be discussed in #32.
