### ISSUE TITLE
Tag on homepage not responsive

### ISSUE THREAD

**Issue by MRX1621** [danieljancar/chorizo#47]
## Tag on homepage not responsive

If tag is to long, then not responsive anymore

- Package: course 

## Expected Behavior
long tags should be responsive

## Actual Behavior
long tags are not responsive

# Additional Information
<img width="452" alt="image" src="https://github.com/danieljancar/chorizo/assets/78649308/d7979813-c845-45aa-a76a-8add9fd352d4">

**Comment by Atharva3008** [comment]
Hello, I would like to take up this issue.

**Comment by danieljancar** [comment]
Hey @Atharva3008,
Thanks for your interest in contributing. We already started developing on this issue, so it's not needed. You're welcome to work on some other issues especially those tagged with `help wanted`. ❤️

**Comment by Atharva3008** [comment]
Okay, great! Thanks
